### ISSUE TITLE
i cant fly with angel rings 

### ISSUE THREAD

**Issue by yangxaolong** [AllTheMods/ATM-1#100]
i cant fly with angel rings or anything  how can i fix it

**Comment by BloodWorkXGaming** [comment]
Do you have enough GP? And do you use the the default Angel Ring or the
Baubles one?
Either way, you could use batwings if the Angel wings don't work.

yangxaolong <notifications@github.com> schrieb am Fr., 10. Nov. 2017, 15:25:

**Comment by yangxaolong** [comment]
bloodworkxgaming thanks
tried a draconic plate and that works for me but thanks anyway
