### ISSUE TITLE
[4.0] can't craft crossroad gear(that's main energy conductor of crossroad )

### ISSUE THREAD

**Issue by Nanawith7** [AllTheMods/ATM-1#108]
seems like this is an issue (or not really an "issue") of unidict
can i ask for fix?

**Comment by BloodWorkXGaming** [comment]
I think I already fixed that, are you sure you have the scripts folder on
the server you are probably playing on?

Nanawith7 <notifications@github.com> schrieb am Do., 15. Feb. 2018, 13:11:

**Comment by Nanawith7** [comment]
~~i checked it and nothing there...~~
~~problem would be solved by reinstalling, sorry for inconvenience~~
i clean installed it and still can't craft crossroad gears
yeah there is 2 recipes for gear,but both make substratum gear

**Comment by BloodWorkXGaming** [comment]
liiiiiiittle late, but there is this recipe for it. 
![image](https://user-images.githubusercontent.com/8137062/38058270-9342f904-32e2-11e8-838a-928955c8248a.png)
