### ISSUE TITLE
Thaumcraft issues

### ISSUE THREAD

**Issue by soulfrezz** [AllTheMods/ATM-1#111]
is any body having any trouble making a crucible ? I right click on it with the mundus and nothing happen

**Comment by MochaDF** [comment]
Yeah, I'm getting this glitch too I haven't found anything to fix it though.

**Comment by soulfrezz** [comment]
I fixed the problem by manually updating thaumcraft to the latest version

**Comment by BloodWorkXGaming** [comment]
will be updated next version
