### ISSUE TITLE
Game crash - Sigil of Augmented Holding - Blood Arsenal

### ISSUE THREAD

**Issue by FuzzBallJack** [AllTheMods/ATM-1#112]
**Issue description**
Holding (Selected player inventory item) or hovering over the sigil of Augmented Holding from Blood arsenal is crashing the game.

**Ways of reproducing**
- Start new creative world
- Spawn in Sigil of Augmented holding - Blood Arsenal
- Mouse Hover over Sigil of Augmented Holding
- Game client locks up and crashes

**Crash reported issue**
`
errorjava.lang.NullPointerException: Unexpected error at arc.bloodarsenal.item.sigil.ItemSigilAugmentedHolding.getHighlightTip(ItemSigilAugmentedHolding.java:55)
	at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:629)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:170)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
`

**Versions**
All the mods Version 3.02
Blood Arsenal Version 1-10.2 - 2.1.0-22
Blood Magic: Alchemical Wizardry Version 1.10.2-2.1.11-80

**Comment by Boomflex** [comment]
Please report this to the Blood Magic devs: https://github.com/WayofTime/BloodMagic/issues

Thanks.
