### ISSUE TITLE
Can't install through Technic Launcher.

### ISSUE THREAD

**Issue by Silverex240** [AllTheMods/ATM-1#115]
When I click the install button in Technic is says
 "Error downloading a File for the following pack:All The Mods Full - Official
Failed to download http://allthepacks.com/cdn/ATM_Full_3.02.zip
Please consult the modpack author"
I am running Windows 10 64 Bit, Java 1.8.0_181 64-Bit, with 12 gigs of ram allocated to Technic out of my 20 total.

**Comment by BloodWorkXGaming** [comment]
We don't support technic.
Please use twitch or multimc.
