### ISSUE TITLE
IC2 major issue and cant launch game

### ISSUE THREAD

**Issue by Cobalt140** [AllTheMods/ATM-1#12]
I've been trying to get this mod pack to work on my desktop for the past week but i don't know what is wrong. I have looked through logs, uninstalled and re-installed the game, launcher, all my java and windows 10(i had just done so anyways so no big deal) nothing had solidly fix it.
when I reinstalled windows it worked for a bit and I was able to play and everything but now it can't launch the game anymore again. sometimes it will crash gracefully (but with no good popup as to why). but most of the time it will blue screen my machine. if you can help I would greatly appreciate it would greatly appreciate it[
[2017-04-11-2.log.gz](https://github.com/AllTheMods/ATM-1/files/915096/2017-04-11-2.log.gz)
[2017-04-11-3.log.gz](https://github.com/AllTheMods/ATM-1/files/915098/2017-04-11-3.log.gz)
[2017-04-11-4.log.gz](https://github.com/AllTheMods/ATM-1/files/915097/2017-04-11-4.log.gz)

](url)

**Comment by Cobalt140** [comment]
[latest.txt](https://github.com/AllTheMods/ATM-1/files/915101/latest.txt)

**Comment by BloodWorkXGaming** [comment]
First of all, you got a pretty outdated java version:
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on
Windows 10:amd64:10.0, installed at
C:\Users\johnf\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25

It is like 121 by now.

And how much ram did you assigne to your game?

john friesen <notifications@github.com> schrieb am Mi., 12. Apr. 2017,
03:07:

**Comment by Cobalt140** [comment]
well i feel silly for the first one.
i assigned 6.4 Gb

**Comment by Cobalt140** [comment]
so i have downloaded the new java. and i have redirected it to look at it.
it launches in the old minecraft launcher now and i get this
[crash-2017-04-11_21.45.09-client.txt](https://github.com/AllTheMods/ATM-1/files/915165/crash-2017-04-11_21.45.09-client.txt)

also just curios is there a way to get this one ...
C:\Users\johnf\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25 
to update? bc twitch and minecraft put that one there

**Comment by OrdinatorStouff** [comment]
![image](https://cloud.githubusercontent.com/assets/6283913/24944294/594bc394-1f0f-11e7-8005-9ab3f4a2fd93.png)

In the Curse/Twitch settings for Minecraft, select "use jar launcher" option and then in the dropdown below that you can manually specify an installed version of java to force it to use.

But for the original issues; no game should be causing a BSOD in Windows... I would highly recommend running a RAM/Memory diagnostics.

**Comment by BloodWorkXGaming** [comment]
Well, you got the new Version of java now which is good, `Java Version: 1.8.0_121, Oracle Corporation`

Why you are getting the IC2 error now is pretty weird tho, are you on the latest version of the pack? if no, update it, if yes, you could give downgrading your IC2 a shot (or remove it completely)

**Comment by Cobalt140** [comment]
so it works for a bit but crashes with this now.
[gameoutput.txt](https://github.com/AllTheMods/ATM-1/files/918264/gameoutput.txt)
i ran a Memory diagnostics but it said there were no issues.
im trying to play on a server with my friends. the version we are using is 2.3.
Is there anything else you can suggest?

**Comment by OrdinatorStouff** [comment]
Your entire JAVA VM is crashing: "EXCEPTION_ILLEGAL_INSTRUCTION" -- something is not okay with your hardware. CPU is too overclocked or running to hot, or RAM is bad or Something quirky on the motherboard with power regulators -- could be anything, but especially combined with your reference that things tend to run smoother right after a fresh Windows install is more telltale as well.

**Comment by PotDucky** [comment]
Almost definitely a hardware issue, most likely to be a memory issue. Run Memtest, check thermals, check cpu clock.
