### ISSUE TITLE
2.54 Digital miner keeps disappearing

### ISSUE THREAD

**Issue by HammerDave** [AllTheMods/ATM-1#16]
Playing SSP, I have a digital miner placed in world.  Save / shutdown / restart, and it's gone.
This has happened a couple times now.

**Comment by BloodWorkXGaming** [comment]
Ye, we are aware of this bug, but there isn't much we can do on our end.
Adding a chunk loading upgrade sometimes helps, but doesn't fix the problem
completely.

Just cheat it back in when it happens

HammerDave <notifications@github.com> schrieb am Di., 16. Mai 2017, 19:05:

**Comment by HammerDave** [comment]
Thanks for the fast update!  I thought as much, but I work in software and know the importance of bringing it up in case there were something that could be done.  :)

**Comment by PotDucky** [comment]
Unfortunately nothing we can do to fix this, Using a chunkloader upgrade can help somewhat but not always. has apparently been fixed in 1.11 versions of mod but unlikely to be backported.

https://github.com/aidancbrady/Mekanism/issues/3718
