### ISSUE TITLE
Player Unable to join

### ISSUE THREAD

**Issue by broeredaan** [AllTheMods/ATM-1#17]
Hello players seem to be unable to join at the momen. This is what players get when they try to join. 
`Internal Exception: java.lang.IllegalArgumentException: The name extrautils2:synergy has bene registered twice, for Block(null) and Block(extrautils2:synergy)`

Any idea whats happening here?
The version is 2.55d

Thank you.

**Comment by BloodWorkXGaming** [comment]
On a server I guess?

Go to the config, and delete the extrautils2.cfg Eith lowercase letters,
and rename the ExtraUtils2.cfg to all lowercase letters like the other one,
and then restart the server.
That should fix the issue...
Sorry for the inconvenience.

Daan Broere <notifications@github.com> schrieb am Mi., 17. Mai 2017, 13:28:

**Comment by broeredaan** [comment]
Did just that but sadly still
https://gyazo.com/ed04f923bf6b9a705b5253d12e643b2a

**Comment by BloodWorkXGaming** [comment]
Ah wait, that is a different error that usual... Try deleting both
extrautils2.cfg configs on your client and server and then start both

Daan Broere <notifications@github.com> schrieb am Mi., 17. Mai 2017, 13:51:

**Comment by broeredaan** [comment]
Was actually doing just that right now and it seems its atleast doing somethin different with exactly that so i'm hopeful ^^
17.05 13:56:59 [Server] Server thread/ERROR [FML]: There are unidentified mappings in this world - we are going to attempt to process anyway
17.05 13:56:59 [Server] Server thread/ERROR [FML]: Unidentified block: extrautils2:synergy, id 2570
17.05 13:56:59 [Server] Server thread/ERROR [FML]: Unidentified item: extrautils2:synergy, id 7985
17.05 13:56:59 [Server] Server thread/INFO [FML]: Using fml.queryResult confirm to answer the following query:
17.05 13:56:59 [Server] INFO Forge Mod Loader detected missing blocks/items.
17.05 13:56:59 [Server] INFO If you continue the missing blocks/items will get removed.
17.05 13:56:59 [Server] INFO A world backup will be automatically created in your saves directory.
17.05 13:56:59 [Server] INFO Missing Blocks/Items:
17.05 13:56:59 [Server] INFO extrautils2:synergy
17.05 13:56:59 [Server] INFO extrautils2:synergy

**Comment by BloodWorkXGaming** [comment]
Ye that is, because you now have an additions block in your world, forge
autosaves there everytime.

Daan Broere <notifications@github.com> schrieb am Mi., 17. Mai 2017, 13:56:

**Comment by broeredaan** [comment]
Seems that doing this serverside only doesnt fix the issue. Now testing it on client.

**Comment by BloodWorkXGaming** [comment]
Ye, that is for sure, because now your server had more items than your
client

Daan Broere <notifications@github.com> schrieb am Mi., 17. Mai 2017, 14:02:

**Comment by broeredaan** [comment]
On a side note:
console is getting this for spam
17.05 14:07:36 [Server] ic2-poolthread-8/WARN [IC2.EnergyNet]: Tile appeng.integration.modules.ic2.IC2PowerSinkAdapter@71ca316d (BlockPos{x=-1979, y=8, z=-4628}), sub tile BlockPos{x=-1979, y=8, z=-4628} (appeng.integration.modules.ic2.IC2PowerSinkAdapter@71ca316d) addition is conflicting with a previous registration at the same location

**Comment by BloodWorkXGaming** [comment]
Break the block and replace it, not much we can fix there on our end.

Daan Broere <notifications@github.com> schrieb am Mi., 17. Mai 2017, 14:06:

**Comment by broeredaan** [comment]
Okay deleting in client seems to fix it. Perhaps it would be nice to have a quick hotfix 2.55e so my players wont have to manually remove that file to join.

**Comment by BloodWorkXGaming** [comment]
Ye, probably... Too many versions...

Daan Broere <notifications@github.com> schrieb am Mi., 17. Mai 2017, 14:09:

**Comment by PotDucky** [comment]
I believe this is all fixed as of 2.55e , please open a new issue if problem persists.
