### ISSUE TITLE
Mekanism Armored Jetpack Craft Bug

### ISSUE THREAD

**Issue by RoslynMC** [AllTheMods/ATM-1#19]
Crafting this item will cause crash when steel block and regular mekanism jetpack entered the crafting grid together.

**Comment by BloodWorkXGaming** [comment]
I'm guessing you are using a tinkers table? If ye, the rendering of the
item might be causing the issue if you are not on the latest version.

RoslynMC <notifications@github.com> schrieb am Do., 18. Mai 2017, 02:25:

**Comment by RoslynMC** [comment]
Yes it was on Tinker's Table. I am using latest version as well. I guess its an easy work-around to use diff crafting table. Thanks for the response though :)

**Comment by PotDucky** [comment]
Known, Tinkers/Mekanism Crafting issue. Unfortunately nothing we can do to solve. Temporarily changing tconstruct.cfg to not render items in world will alloy you to load into world and remove items from crafting table.
