### ISSUE TITLE
Advanced Rocketry Motor/LibVulpes Motor Issue.

### ISSUE THREAD

**Issue by RoslynMC** [AllTheMods/ATM-1#20]
LibVulpes Motor(s) does not work with construction of advanced rocketry machinery despite LibVulpes being a AdvRock. dependency.

**Comment by PotDucky** [comment]
This is due to LibVulpes and Advanced Rocketry being different versions. (as latest Advanced Rocketry was crashing serverside). AR has since updated so next modpack version will fix this.

**Comment by PotDucky** [comment]
Fixed as of 2.56+ , Thank you for report.
