### ISSUE TITLE
Can not use sponge

### ISSUE THREAD

**Issue by TheRealM18** [AllTheMods/ATM-1#21]
when i go to use sponge it comes up with this error:

https://pastebin.com/bk3043bW

i put it into pastebin so that it is easier to read.

**Comment by PotDucky** [comment]
Unfortunately we cannot in anyway support sponge due to mod incompatibilities. It is possible to get the server to launch using workarounds designed for Applied Energistics. But from my own testing you will find lots of little bugs in lots of mods.
