### ISSUE TITLE
Combination of upgrades on Ender IO's Dark Steel Armour causes player to spasm. [ATM1]

### ISSUE THREAD

**Issue by Poshtester63** [AllTheMods/ATM-1#22]
The upgrades I have on the Dark Steel Armor are:

Helmet: Empowered II (The Double-Layer capacitor)
Chestplate: Empowered II, Elytra
Leggings: Empowered II, Speed III
Boots: Empowered II, Jump III, Flippers, Apiarist

Attempting to fly with the Angel Ring, while sprinting causes player to spasm. The speed effect doesn't apply when flying, as a result of this. Taking the leggings off, or slowing down to normal pace, removes the screen shaking/spasming.

Also, elytra, and jump upgrades, and flight are not compatible with each other. Attempting to fly, and then falling down has mixed results, based on whether all 3 'mini-jumps' were used prior to flight.

**Comment by PotDucky** [comment]
Yeah, have confirmed this myself but not a lot I can do to change it. A similar sort of bug has been reported on EnderIO Github, so you could perhaps add this to there.

**Comment by Ravalli03** [comment]
I also have the same issue but didn't have this issue when using the same armor setup in foolcraft mod pack, which leads me to believe its something in this pack causing it, its like the screen wanting to zoom in when using any speed upgrade but instead is zooming in and out. Will keep an eye on the ender io github issue.
