### ISSUE TITLE
Immersive Engineering blueprints recipe suggestion.

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-1#25]
There are three blueprints, common projectiles, specialized projects and arc furnace electrodes. The only one that can be made is the common projectiles blueprint. Do you think it is possible to make recipes for the other two? Or would that unbalance things?

**Comment by BloodWorkXGaming** [comment]
Good idea actually, thanks, since it is shitty for a rather big server when it is quite explored already
