### ISSUE TITLE
2.52b Mekanism can't receive/transmit power to/from RF providers/users.

### ISSUE THREAD

**Issue by Landrash** [AllTheMods/ATM-1#3]
Mekanism can't receive/transmit power to/from RF providers/users.

Unsure if this is on purpose but this haven't always been the case with Mekanism.

Easy to replicate:
Mekanism generator -> EnderIO Capacitor bank. Capacitor bank won't charge.

**Comment by autumnfire** [comment]
Reading from [here](https://www.reddit.com/r/allthemods/comments/5wzrau/how_do_i_transfer_20000_rft_without_flux_networks/) it looks like its a Mekanism issue with other mods.

**Comment by Landrash** [comment]
Link in question doesn't mention any bugs @autumnfire ?

**Comment by autumnfire** [comment]
Second reply mentions it. I'll paste it here:
> About the universal cables, I've had quite a few problems with them in 1.10 where they don't seem to transfer power to machines from other mods like Ender IO. It works with Mek machines and IC2(once I enable EU) but doesn't send power to some machines from mods like AE2, Actually Additions, and Ender IO, even if they appear connected. So I'll probably skip those.

**Comment by jezzen** [comment]
I think it's been like this for a little while now. What I've been doing, unless the update changed something about it (haven't played yet), is to use an energy cube with the output set towards an RF machine and it converts properly. Also, Mekanism machines have been accepting RF from enderIO cables fine. Again, unless the update changed something about this.

**Comment by PotDucky** [comment]
Yeah, nothing we can do about this, team behind Mekanism is working on a Tesla rewrite so should be fixed once that's around. Basically don't use Universal Cables.
