### ISSUE TITLE
2.55e: TechReborn rubber sapling has no texture

### ISSUE THREAD

**Issue by bernds** [AllTheMods/ATM-1#33]
(The mod was downloaded with CMPDL and imported into MultiMC, in case that makes a difference)

When planting a TechReborn rubber sapling, it appears as a cube with the black/pink "no texture" appearance.

**Comment by PotDucky** [comment]
I didn't personally have this issue before, But TechReborn has been updated and i'm unable to replicate the issue so i'll assume it's fixed as of 2.56. Re-open issue if you're still having the problem and we can look into it.
