### ISSUE TITLE
Reborn Storage multiblock disconnecting from RS network after restart or disconnect.

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-1#34]
If I disconnect or restart the server I need to go down and remove the Refined Storage cable connecting to it and break one or two blocks. To make it connect properly again I have to place the blocks first then connect the Refined Storage cable. I don't know if this is a bug directly related to the mod or something, but I thought it would be worth mentioning.

**Comment by BloodWorkXGaming** [comment]
thanks for reporting, but afaik this is something raoul, the dev of RS is aware of. Nothing we can change on our end tho
