### ISSUE TITLE
Practical Logistics 2 item duplication

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-1#35]
Sometimes if items shown on the screen is right clicked it is duplicated instead of actually being removed from the inventory. I tested it with a few different blocks and as long as I put it inside the chest I could infinitely duplicate it. I managed to recreate the duplication when some of the items that were removed were still shown on screen, if you break the screen and place them down again you can duplicate the items.

**Comment by BloodWorkXGaming** [comment]
Can't replicate, maybe it was fixed?
