### ISSUE TITLE
Keybind screen pops up every 5 seconds and I can't get rid of it.

### ISSUE THREAD

**Issue by Xingor** [AllTheMods/ATM-1#39]
Hi. I've been playing  All The Mods for a couple weeks now. This just started happening today and I don't know why. http://imgur.com/a/uVtSj

**Comment by BloodWorkXGaming** [comment]
That is indeed strange, that is modular power armor keybindings screen, check in your configs whether there is a key assigned to it.

If nothing helps and you are playing in singleplayer you could just remove that mod/reinstall the pack.

**Comment by Xingor** [comment]
Somehow I got it to stop. I had modular powersuit unbinded. I rebinded to keys I don't use and restarted and that finally stopped it.

**Comment by BloodWorkXGaming** [comment]
Good that it is fixed!
