### ISSUE TITLE
Crushed Nether Quartz oreDict

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-1#40]
dustQuartz from some mods, dustNetherQuartz for AE2

**Comment by RoslynMC** [comment]
So you are wanting other quartz dust types to work for AE2 if I am understanding this small statement correctly?

**Comment by OrdinatorStouff** [comment]
Sorry, I'm one of the pack devs so I was more making this issue tracker so we don't forget to look into it. Basically there is two oredict entries for crushed nether quartz, but not all crushed nether quartz items are registered to both oredict so some recipes only work with one type and they can't be converted freely back and forth. 

We've very thorough with unifying oredictionary registries to prevent inconvenience issues like this thus why I wanted to make the issue here so we can fix it in a release or two.

**Comment by BloodWorkXGaming** [comment]
added
