### ISSUE TITLE
Crossroads gears recipe and Tinkers Alloying Tiberium bug

### ISSUE THREAD

**Issue by KoloXD** [AllTheMods/ATM-1#41]
Greetings,
It would seem that the gears from Crossroads doesn't have a recipe and normal gears aren't working with the mod (probably because of the special properties).

Also Tiberium from the Tinkers Alloying Addon drops Tiberium crystal with missing textures/icon and the Smeltery melts it into Dilithium instead of Tiberium.
![image](https://cloud.githubusercontent.com/assets/29026973/26532541/5e0d506e-4403-11e7-9f6c-96c5fded2776.png)

**Comment by Ravalli03** [comment]
I also have this missing texture bug. But as far as the smeltery turning it into Dilihium, as per the recipe, it's what it shows. After looking into it, you have to silk touch Tiberium and use another machine to get Tiberium fluid.

**Comment by BloodWorkXGaming** [comment]
Crossroads gears work like this, might not show up in JEI tho
![image](https://cloud.githubusercontent.com/assets/8137062/26731992/473f173a-47b6-11e7-8778-572168701661.png)

The tinkers bug is something we might not be to fix on our end sadly as we can't change the drops of a block.

**Comment by KoloXD** [comment]
Much appreciated, i'll give this crafting recipe a try, JEI indeed does not show this.

**Comment by BloodWorkXGaming** [comment]
crossroads working, tinkers is not fixable on our side
