### ISSUE TITLE
ArmorPlus The Gift Of The Gods Bug

### ISSUE THREAD

**Issue by alentoghostflame** [AllTheMods/ATM-1#42]
The item "The Gift Of The Gods" from ArmorPlus, when used, is supposed to give any item in the entire modpack. It has 2 uses, but doesn't seem to work at all. Making it in survival mode yielded no results. Same with spawning 20 of them in.

**Comment by RoslynMC** [comment]
Does it have a item black list in the configuration/Config edit?

**Comment by jezzen** [comment]
pretty sure its disabled in atm default settings. stupid that it doesnt remove the recipe though

from armorplus config:

thegiftofthegods {
    # Set the cooldown ticks until you can use The Gift Of The Gods (1 second = 20 ticks)
    I:cooldownTicks=600

    # Enable/Disable The Gift Of The Gods
    B:enableTheGiftOfTheGods=false

    # Set the max amount of uses for the item
    I:maxUses=2
}

**Comment by BloodWorkXGaming** [comment]
properly disabled crafting till we get around making a whitelist
