### ISSUE TITLE
Akashic Tome all guides glitch

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-1#44]
After you have made the Akashic Tome and have added one book to it. Then you can put it in the crafting table and you'll be able to make it into one that holds all the guides. I doubt it is meant to do that so I thought I'd mention it.

**Comment by BloodWorkXGaming** [comment]
Thanks for reporting, but somehow craftweaker doesn't want to make it work in the intended way, it isn't that big of a problem anyways ^^
