### ISSUE TITLE
Random Things water walking boots

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-1#46]
I am not certain of this, but it seems as if the water walking boots from random things does not spawn in dungeon or stronghold chests. This isn't really that important but I thought I should mention it.

**Comment by Ravalli03** [comment]
They can be crafted

**Comment by TheKrister2** [comment]
Not for me at least, I added a custom recipe instead though so it's fine. I thought I should mention it, I am using the latest release so I don't think that is the issue either but oh well.

**Comment by Ravalli03** [comment]
Maybe it was a different mod I'm thinking that had water walking boots, then again I crafted them before the last update

**Comment by TheKrister2** [comment]
You might be thinking of Cyclic's boots of Elitch, they also allow you to walk on water. But as far as I know there isn't any default recipe for Random Things water walking boots. Other than the water walking potion those are the only things I know of that allows one to walk on water.

**Comment by BloodWorkXGaming** [comment]
As you suggested yourself, just use the cyclic boots of Elitch which have the same effect and are craftable.
(Pretty easy due to ArmorPlus actually.)
