### ISSUE TITLE
2.57 ores missing from Void Ore Miner

### ISSUE THREAD

**Issue by zeeZ** [AllTheMods/ATM-1#47]
I noticed a lack of NuclearCraft ores from the Void Ore Miner, so I compiled a list of ores with an OreDict name of ore* that, according to JEI, spawn in the overworld, but are not generated by the Void Ore/Resource Miner:

#### ArmorPlus 
- oreLavaCrystal

##### Ars Magica 2
- oreSunstone

##### Modular Force Field Systems
- oreMonazit

##### NuclearCraft
- oreThorium
- oreBoron
- oreLithium
- oreMagnesium

##### TechReborn
- oreGalena

#####  Tinkers Alloying Addon
- oreDuranite
- oreVibranium
- oreKarmesine
- oreOvium
- oreJauxum
- oreEezo

I'm not adding a minable.json PR because I don't think I'd choose the right colors and weights for those ores (and not because I'm lazy ;) ). There may also still be some ores that are no longer in the pack, but I didn't compile a list of those (because I'm lazy).

**Comment by BloodWorkXGaming** [comment]
Cool, thanks for the list, will add them next patch.

Christian <notifications@github.com> schrieb am Fr., 16. Juni 2017, 19:18:

**Comment by Ravalli03** [comment]
Also, the thermal mods have added new ores, maybe add those when the pack gets the thermal updates

**Comment by BloodWorkXGaming** [comment]
Added except some of the TAIGA ores to still provide a challenge when looking for them, thanks for creating the list
