### ISSUE TITLE
[Botania] Missing Recipe/Broken 

### ISSUE THREAD

**Issue by RoslynMC** [AllTheMods/ATM-1#49]
botania:floatingSpecialFlower types to generate mana/fuctioning flowers cannot be crafted. Recipes are missing.

**Comment by BloodWorkXGaming** [comment]
They can be crafted when you craft one of the normal floating flowers together with the functional flower you wanna have.
![image](https://user-images.githubusercontent.com/8137062/27393094-9648e490-56a8-11e7-9f75-18ebc62fe3cd.png)
