### ISSUE TITLE
2.52b [Draconic Evolution] Fusion Crafting Injector doesn't receive energy.

### ISSUE THREAD

**Issue by siamon-fr** [AllTheMods/ATM-1#5]
Hello,

I've tried with every battery/conduit/cable but or draconic crystals; impossible to feed energy in that block that is requiered to craft Draconic evolution items.

Ty!

**Comment by BloodWorkXGaming** [comment]
Can you please send a Screenshot of your setup?

siamon-fr <notifications@github.com> schrieb am Mi., 22. März 2017, 22:52:

**Comment by BloodWorkXGaming** [comment]
Just to make sure, are you powering the blocks that you put the items in or the main crafting block in the center?

**Comment by PotDucky** [comment]
Unable to reproduce, No issue with mod likely just setup crafting incorrectly. Watch tutorial or come into discord if you need help. https://discord.gg/p4BZStd
