### ISSUE TITLE
Thermal Dynamics

### ISSUE THREAD

**Issue by Leurak** [AllTheMods/ATM-1#50]
Thermal Dynamics is out now, so it should be added to the pack.

**Comment by MCHellspawn** [comment]
And mine factory reloaded

**Comment by ozhound** [comment]
TD is being added in the next update

**Comment by Ravalli03** [comment]
@leurek, there is an open post for requesting mods #9. TD has already been suggested.

**Comment by Leurak** [comment]
@Ravalli03 Okay
