### ISSUE TITLE
Server Unable to Start after latest update.

### ISSUE THREAD

**Issue by thefinaldegree** [AllTheMods/ATM-1#51]
After the 2.57 update, the server won't start even with a fresh install.
Crash log: https://pastebin.com/9eWDr2R3
This is from a completely fresh install.

**Comment by BloodWorkXGaming** [comment]
Could be a problem with reading permissions, hasn't happened to anyone else so far afaik

**Comment by thefinaldegree** [comment]
I thought that might have been the problem, so I chmod'd the whole directory as 777 to be safe, no change

**Comment by BloodWorkXGaming** [comment]
Try reinstalling the pack, might be a corrupted jar file.
