### ISSUE TITLE
IndustrialCraft2 didnt show correct on nei

### ISSUE THREAD

**Issue by Bigevildog666** [AllTheMods/ATM-1#52]
![2017-06-24_13 27 44](https://user-images.githubusercontent.com/476225/27508251-1ff10968-58e1-11e7-8155-37a60bd1ecd0.png)
![2017-06-24_13 27 47](https://user-images.githubusercontent.com/476225/27508253-20155048-58e1-11e7-9656-afe570c29c08.png)
![2017-06-24_13 27 42](https://user-images.githubusercontent.com/476225/27508252-20150d72-58e1-11e7-8620-909b154e671e.png)

I noticed that IndustrialCraft2 didnt show correct on nei.

**Comment by RoslynMC** [comment]
Yeah I noticed that all IC2 items are referenced by their full entry instead of their item name. Kind of spammy to the eyes.

**Comment by Ravalli03** [comment]
Same for me also.

**Comment by Bigevildog666** [comment]
Here a little Fix for the Problem

Just Update MFR


https://forum.industrial-craft.net/thread/14780-item-names-and-tool-tips-completely-screwed-up/

**Comment by BloodWorkXGaming** [comment]
Fixed in the new version
