### ISSUE TITLE
Revert Chisels-and-Bits to The Last Release Version 12.12

### ISSUE THREAD

**Issue by Skid-Inc** [AllTheMods/ATM-1#53]
Unless there was a specific reason you updated Chisels and Bits to the 12.14 beta version, I would suggest you revert back to 12.12 release version. The beta version was causing major clunk update lag in my world, see this bug report: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/282

**Comment by CaptainSisko** [comment]
This issue was resolved in Chisels and Bits version 12.15.

Can we get Chisels and Bits updated instead of reverted?

**Comment by Dylanavo** [comment]
Had this issue also. Updating to 12.15 fixed it.

**Comment by Dylanavo** [comment]
Had this issue also. Updating to 12.15 fixed it.
