### ISSUE TITLE
1.10.2 - Random things - ectoplasm doesn't drop?

### ISSUE THREAD

**Issue by Drachlox** [AllTheMods/ATM-1#54]
Playing on 1.10.2
So i've tried killing the spirits using potion of harming 2.
They die, but no ectoplasm.

Got tired of making potions (have used around 18 potions so far), so i bound a potion to the potion-wand from more wands. It still killed the spirits, but no ectoplasm drops.

Am i doing something wrong? Are the ectoplasm drop% just insanely low?

Finally: got tired of chasing the spirits.
Caught one of them in a spawner changer, clicked it on a vanillaspawner, used drop of evil on that to get a resturbed mob spawner (extrautils2) that spawns spirits.
Gave it 20 speed upgrades, set up a mechanical user to spam the room with instant harming splashpotions.

Still no drops.

**Comment by InflamedSebi** [comment]
Can't reproduce (v3.0b). Maybe something went wrong on your update?

**Comment by BloodWorkXGaming** [comment]
Can't replicate, drops for me on the new version
