### ISSUE TITLE
Issue on ATM 1 version 3.00b release

### ISSUE THREAD

**Issue by FreeVilly** [AllTheMods/ATM-1#57]
I placed an Oak boat on the server then my game crashed being unable to reconnect to the server.
Here is the crash report:
https://pastebin.com/1H2j3zWs

The exact same issue happened to my friend on the server who also placed an Oak Boat.

Anyone have an idea how to fix this?

**Comment by RoslynMC** [comment]
Delete chunk possibly? I tried to replicate this but could not. What did you place this Oak Boat on?

**Comment by FreeVilly** [comment]
@RoslynMC how do you delete a chunk?

**Comment by BloodWorkXGaming** [comment]
Can't replicate, maybe was fixed.
