### ISSUE TITLE
Pressurized Reaction Chamber

### ISSUE THREAD

**Issue by daria53081** [AllTheMods/ATM-1#63]
Someone on my server created a pressurized reaction chamber from Mekanism and now it is crashing the server every time someone goes near it or when they log in.  Not sure what the error is and I am unable to clear the item.

**Comment by BloodWorkXGaming** [comment]
Was is crafted in a tinkers table? If yes, then set in world rendering from
tinkers to false

daria53081 <notifications@github.com> schrieb am Do., 6. Juli 2017, 17:09:
