### ISSUE TITLE
Cyclic's Magic Beans are OP

### ISSUE THREAD

**Issue by sshawnsamuell** [AllTheMods/ATM-1#64]
Currently magic beans can drop a relatively small selection of vanilla blocks and items, including Nether stars, and don't seem to have any weighting to them. They are very cheap, only needing one of each vanilla seed and an emerald for 2 and have a 100% chance of dropping another at maturity. just one IRL night with a dozen or so plants gained me 250+stars.
Recipe, drop table, and seed duping need to be looked at.

**Comment by BloodWorkXGaming** [comment]
Huh... I thought we actually removed the stars out of the loot table
already...

sshawnsamuell <notifications@github.com> schrieb am Do., 6. Juli 2017,
21:55:

**Comment by BloodWorkXGaming** [comment]
nerfed in #9df2049a965bee9a27b51ef1b708c04404ba43fb
