### ISSUE TITLE
Ore Excavation

### ISSUE THREAD

**Issue by daria53081** [AllTheMods/ATM-1#65]
I know that in the last patch Ore Excavation was added.  It does not seem to be working.  I rebounded the key to something that is not conflicting and it is still not working.  Other members on the server did the same and are running into the same problem.

**Comment by BloodWorkXGaming** [comment]
Well, then none of your server members read changelogs... You need the
modifier or the enchantment....

daria53081 <notifications@github.com> schrieb am Fr., 7. Juli 2017, 23:59:
