### ISSUE TITLE
Mekanism Boiler casing recipe overrides Steel gear recipe

### ISSUE THREAD

**Issue by BarsikTheCaT** [AllTheMods/ATM-1#69]
Playing on ATM 3.0b

**Comment by BloodWorkXGaming** [comment]
This is already fixed, did you forget to copy the scripts to the server?

BarsikTheCaT <notifications@github.com> schrieb am Di., 11. Juli 2017,
11:59:

**Comment by BarsikTheCaT** [comment]
I guess I'll report this to a server admin
