### ISSUE TITLE
Railcraft Copper Plates

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-1#7]
Railcraft copper plates are craftable with 2x2 of ore:copperIngot but can't be used and can't be converted since themselves are not oredict with plateCopper. They don't even have a smeltery melting recipe or anything.

recommend: remove recipe for railcraft copper plates (since it's the "easiest" recipe anyway) or <ore:plateCopper>.add(<railcraft:plate:3>);

**Comment by BloodWorkXGaming** [comment]
just gonna remove it, most of the railcraft stuff that uses plates isn't implemented anyways yet...
Thanks ^^

**Comment by BloodWorkXGaming** [comment]
closed by commit 6661906e3f9b73ce7f38f42da41637900ec4b018
