### ISSUE TITLE
Mekanism Advance Fluid Tank Crash

### ISSUE THREAD

**Issue by Biggercheese** [AllTheMods/ATM-1#70]
Crafted the Advanced Fluid Tank from Mekanism and it crashed my client. Server operates fine. Any attempt to reconnect immediately crashes Minecraft.

**Comment by Biggercheese** [comment]
I was crafting using the Tinkers crafting bench.

**Comment by Biggercheese** [comment]
I'll include a link to the crash report on pastebin. Was trying to work with my server host but they want to roll back the server 12 hours.

https://pastebin.com/uUJHCDL5

**Comment by Biggercheese** [comment]
If i reset my location I can load in perfectly fine. Once I get too close to my house the game crashes again with the previously included crash report.

**Comment by BloodWorkXGaming** [comment]
Disable the rendering on the tinkers table

Biggercheese <notifications@github.com> schrieb am Di., 11. Juli 2017,
20:20:
