### ISSUE TITLE
Me- Cable dont get used up

### ISSUE THREAD

**Issue by Gameplayerabc** [AllTheMods/ATM-1#74]
At some point in the lategame, my me cables didnt get used up anymore if I place them.

**Comment by Gameplayerabc** [comment]
Ive discovered that it has something do with the Draconic Evolution Item Dislocator. If its turned on, the cable sometimes get used up, sometimes not_

**Comment by BloodWorkXGaming** [comment]
Can't replicate, please provide further information.

**Comment by Gameplayerabc** [comment]
Honestly, I dont even know how that issue came up. It just happened so to speak. If that helps, Ill try and provide a somehow accurate  list of the items I had in my inventory ( might not be 100% accurate, because I didnt take a screenshot, Ill just try to recall what I had in my inv at the time)

**Comment by BloodWorkXGaming** [comment]
Tbh, you don't really have to, ae2 released a final 1.10 version and unless
it is a really game breaking thing they won't update 1.10 anymore

Gameplayerabc <notifications@github.com> schrieb am Fr., 28. Juli 2017,
12:53:
