### ISSUE TITLE
Massive Frame Drops

### ISSUE THREAD

**Issue by GrafSimsula** [AllTheMods/ATM-1#78]
Hello :)

Im currently playing the All the Mods modpack and im having issues with Massive FPS drops.
When i enter the nether and exit it again my FPS drop from 100+ down ~4 FPS making the game pretty much unplayable. I can circumvent this by setting my render distance to 2 chunks buts than i cannt even see the inside of my base from wall to wall so its not exactly the most convinient fix.

This is the second time this happend. The first time i thought Rouge Liek Dungeons was causing the lag because it started happening as soon as i found the lowest level of a Dungeon, deleted the mod revisited the spot and the laggs / FPS drops stopped and started again when i exited the nether back to the overworld. Im currently still running the All the Mods Modpack with all the mods you download it with except Rougelike Dungeons, also i added OptiFine
[latest.txt](https://github.com/AllTheMods/ATM-1/files/1183474/latest.txt)

Im attaching my latest Log hopefully it helps helping me fix this problem.

**Comment by BloodWorkXGaming** [comment]
Can't replicate, might have been fixed by whatever mod has been causing it.
