### ISSUE TITLE
Nuclearcraft ores only generate in overworld

### ISSUE THREAD

**Issue by HugoZink** [AllTheMods/ATM-1#79]
Nuclearcraft ores only generate in the overworld, and in a select few other dimensions (such as the Extra Utilities 2 Quarry dim). There seems to be no good reason for them to not generate in other dimensions, such as RFTools dimensions. This behavior is unlike any other ore in the pack.

Using Cofh Core's worldgen capabilities, I have managed to accurately replicate Nuclearcraft's ore generation. This should work in all supported dimensions (except The Nether and The End, obviously).

A quick test revealed that the amount of ores in my tweaks are very close to Nuclearcraft's own (tested with Digital Miner and Just Enough Resources). Further tweaks should not be required, but feel free to compare them yourself.

Please consider disabling Nuclearcraft's oregen, and adding this worldgen file for Cofh Core instead:

https://gist.github.com/HugoZink/fd90a89c2f0ba07bf893e9de0dce5330

This json file should be put in `config/cofh/world`. It will be detected automatically.

**Comment by BloodWorkXGaming** [comment]
Thanks for making the file ^^
