### ISSUE TITLE
Inversed condition for restart in ServerStart.sh

### ISSUE THREAD

**Issue by tgalloy** [AllTheMods/ATM-1#8]
Hi,

When the server stop and the script is asking if you want to restart, when you press 'y', it will stop. Just need to change the condition (Actually it's look like this
![erreur serveur](https://cloud.githubusercontent.com/assets/22316248/24578131/6901bf42-16da-11e7-8844-3dd08345ffaa.png)
)

**Comment by BloodWorkXGaming** [comment]
I guess that has been solved by now?

**Comment by ozhound** [comment]
yep, just hasnt been pushed to main branch so we are not including it in
the packs yet.
