### ISSUE TITLE
Duping glitch when using Quantum Entangloporter and Refined Storage Importer

### ISSUE THREAD

**Issue by Scrumdiddly32** [AllTheMods/ATM-1#80]
I've discovered on my server that when a Refined Storage importer is connected to a quantum entangloporter directly, the RS system takes in an infinite supply of whatever item is being transferred via the entangloporter. Tested with wheat, and the storage system filled up at a rate of around 2-3 wheat per second until the importer was broken. Putting a chest in place showed that the entangloporter was holding 6 wheat.

I tested again with dimensional transceivers, and there was no duping. An AE2 import bus didn't work at all when attached directly to the entangloporter (I assume this is intended, though).

Running ATM v3.01

**Comment by BloodWorkXGaming** [comment]
Can't reproduce, doesn't dupe (maybe it was fixed.)
