### ISSUE TITLE
Logistical Sorter Crash

### ISSUE THREAD

**Issue by AedanSkykes** [AllTheMods/ATM-1#83]
How to Reproduce:

Installing a logistical sorter from mekanism into the top of chest, then opening its GUI 
and fiddling with buttons (left and right clicking )especially the round robin button causes the game to crash.

Added Mods: Decocraft-2.4.2_1.10.2.jar

Crash Log
[crash-2017-08-05_03.33.33-server.txt](https://github.com/AllTheMods/ATM-1/files/1202200/crash-2017-08-05_03.33.33-server.txt)

**Comment by BloodWorkXGaming** [comment]
Can't reproduce, was maybe fixed?
