### ISSUE TITLE
Modpack crash when open twelfth page in creative inventory

### ISSUE THREAD

**Issue by LegalHax** [AllTheMods/ATM-1#90]
When i create new creative world and open inventory in twelfth page, game crashes.
[crash-2017-09-19_19.16.30-client.txt](https://github.com/AllTheMods/ATM-1/files/1315237/crash-2017-09-19_19.16.30-client.txt)

**Comment by BloodWorkXGaming** [comment]
So, did you play offline while this crash occurred?
Or did you play on a cracked client or something similar?
